# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define the cluster
nodes = [
  { :hostname => 'testsystem1', :ip => '10.0.0.60'},
  { :hostname => 'testsystem2', :ip => '10.0.0.61'},
  { :hostname => 'testsystem-jumphost', :ip => '10.0.0.62'}
]

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      
      node_config.vm.hostname = node[:hostname]
      node_config.vm.network :private_network, ip: node[:ip]
      
      #node_config.vm.box = "trusty64.box"
      #node_config.vm.box_url = "https://github.com/sepetrov/trusty64/releases/download/v0.0.5/trusty64.box"
      node_config.vm.box = "jasonc/centos7"
      # wholebits/centos7
      node_config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      # install ansible
      node_config.vm.provision "shell", inline: "sudo yum install epel-release"
      node_config.vm.provision "shell", inline: "sudo yum install ansible"      
      node_config.vm.provision :hostmanager

    end
  end

end




