- name: install epel-release
  yum: name=epel-release state=latest
  tags: erlang

- name: install erlang from EPEL
  yum: name=erlang state=latest
  tags: erlang

- name: install rabbitmq
  yum: name=rabbitmq-server state=present

- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled

- name: set rabbitmq cookie
  shell: echo SVTRZKAOOADLOJQAOBJQ > /var/lib/rabbitmq/.erlang.cookie

- name: set owner rabbitmq cookie
  shell: chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie

- name: set rabbitmq cookie  permission
  shell: chmod 600 /var/lib/rabbitmq/.erlang.cookie

- name: make cookie readable
  file:
    path: /var/lib/rabbitmq/.erlang.cookie
    mode: 0600

- name: copy rabbit cluster config
  copy:
    src: ./rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
    mode: 0644
    backup: yes

- name: restart rabbitmq
  shell: sudo service rabbitmq-server restart

- name: add users
  rabbitmq_user: user={{item}} password=changeme tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
  with_items:
  - user1
  - user2

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes  
