- name: remove old logstash downloads
  shell: rm -rf logstash*rpm
  ignore_errors: yes

- name: download logstash
  shell: wget https://artifacts.elastic.co/downloads/logstash/logstash-5.4.2.rpm

- name: install logstash
  shell: sudo rpm -ivh logstash-5.4.2.rpm
  ignore_errors: yes

- name: copy config
  copy:
    src: ./applications.conf
    dest: /etc/logstash/conf.d/applications.conf
    mode: 0644
    backup: yes

- name: restart of logstash
  command: "cd /usr/share/logstash/bin/ && nohup sudo ./logstash -f /etc/logstash/conf.d/ &"

# todo that's a dirty way to do it, changy to normal yum install and use idempotetn commands
