- name: download logstashhttps://artifacts.elastic.co/downloads/logstash/logstash-5.4.1.rpm

- name: install logstash
  shell: sudo rpm -ivh logstash-5.4.1.noarch.rpm

- name: copy config
  copy:
    src: ./applications.conf
    dest: /etc/logstash/conf.d/applications.conf
    mode: 0644
    backup: yes

- name: ensure start of logstash
  shell: sudo systemctl enable logstash.service

- name: restart of logstash
  shell: sudo systemctl restart logstash.service

# todo that's a dirty way to do it, changy to normal yum install and use idempotetn commands



